### PR TITLE
Automated CanBoot "deployer" application

### PR DESCRIPTION
**Pull request by KevinOConnor**
This PR extends the CanBoot build to also generate a "deployer" application.  That is, it can build an application that one may run via an existing bootloader and this application will flash CanBoot to the start of flash.  This can make it easier to flash CanBoot as it can avoid the need for an stlink, openocd, or similar low-level flashing tool.  It also makes it easier to develop CanBoot itself, as one can use an existing installation of CanBoot to flash a new version of CanBoot.

This feature is selected by a new "Build CanBoot deployment application" menu option.  The default is "Do not build".  To enable the feature, one would select the bootloader offset of their existing bootloader.

I have tested this code on lpc1768 and on stm32g0.

I expect this feature will make it much easier for users to deploy CanBoot.  However, there are some things to note:
1. Users really should have a way to manually flash the bootloader if something goes wrong.  I view this feature as a "time saver" not a replacement for an stlink/openocd/etc.
2. I chose the name "deployer.bin", but perhaps there is a better name for the tool/feature.
3. The new build rules for this feature are a bit complex.

Thoughts?
-Kevin

### CODE REVIEW

**Comment by Arksine** [comment]
Nice, I definitely think that this will be useful for getting CanBoot on more devices.  The implementation looks good to me, I'll merge if you are ready.

One question I do have...assuming there is enough flash space, do you think it would be worthwhile to copy the original bootloader somewhere after the deployer?  If something does go wrong it would make recovery a bit easier, we could probably have `buildbinary.py` tell the user where its located.  In cases were the flash did succeed we could have `flash_can.py` read the original bootloader so users have a copy.

An alternative would be to have some testers dump the original bootloader on their device then make them available in case users want or need to revert.

**Comment by KevinOConnor** [comment]
Getting a backup of the original flash was something I considered as well.  Alas, I couldn't think of a way to do that in such a way that would be "accessible" to regular users.

That is, I fear expert users would not need the feature (they'd be able to backup via other means) and novice users would find a multi-step installation process challenging to navigate.  So, I was concerned taking backups may make the "deployer" more fragile or harder to use, and not actually provide much real-world benefit.

FWIW, the Klipper code itself can be used to dump flash (via `debug_read` commands).  I was planning to extend console.py to automate dumping of memory ranges (it's generally useful during development).  That might be a simpler way to get backups - power users could then use Klipper to backup flash.  (The advantage of backing up via Klipper, or similar tool, is it could directly write the flash contents to a file on the host.)

I'm open to alternatives.

As to this PR, it's fine with me to merge when you are ready.

-Kevin

**Comment by Arksine** [comment]
Thanks, it works well in my tests.  I like the idea of having Klipper backup the bootloader.  If we can get power users to create backups that should be all that is necessary.  I think some board manufacturers make their binaries available, but most don't.

**Comment by KevinOConnor** [comment]
Thanks.  I did add DUMP and FILEDUMP commands to console.py (eg, `FILEDUMP mybackup.bin 0x0 0x4000`).  https://github.com/Klipper3d/klipper/commit/49d83bd3e26f4ea768bd978beb300f79f64f1707

-Kevin

**Comment by robthide37** [comment]
So i am a little confused . If a device has  its original bootloader you would select  "Build CanBoot deployment application"  then the proper settings plus the original bootloader size not the new one so ex huvud would be 2kb . Then we would flash with USB using regular beba or leaf command and it will write the bootloader ?  Or did I misunderstand

**Comment by KevinOConnor** [comment]
> If a device has its original bootloader you would select "Build CanBoot deployment application" then the proper settings plus the original bootloader size not the new one so ex huvud would be 2kb . Then we would flash with USB using regular beba or leaf command and it will write the bootloader ?

Yes.

-Kevin

**Pull request merged**
