### PR TITLE
Add support for flashing stm32h7 boards

### PR DESCRIPTION
**Pull request by KevinOConnor**
This PR adds support for stm32h7 boards.  I have tested this with basic USB booting on a "BTT Octopus Pro h723" board.  This PR is on top of #56 - only the last two commits in this PR are specific to the stm32h7.

This PR also enables support for the stm32h743 chips.  However, I have not tested those chips.

Klipper needed some changes in order to reboot directly into canboot.  Be sure to use the latest version of Klipper if testing.

-Kevin

EDIT: The latest version of Klipper now has the necessary changes to reboot into canboot on stm32h7.

### CODE REVIEW

**Comment by idontknowtom** [comment]
Thanks I’ll be testing this in a few hours on a SKR3 with STM32H743

**Comment by idontknowtom** [comment]
@KevinOConnor Just updated Klipper and switched to this CanBoot branch.

Worked 100% flawlessly on the STM32H743 chip (SKR3 EZ). Happy to provide anything additional, if needed. Thanks!

**Comment by Snolte1001** [comment]
@KevinOConnor 
also tested with SKR 3 EZ, upload the Klipper firmware via CAN works without problems ! Thanks Kevin, that helps me a lot!!

**Comment by Arksine** [comment]
I pulled and rebased after merging #56 to resolve the conflict, so this addition is now merged.

**Pull request closed without merging**
